version: '3.8'

services:
  frontend:
    ports:
      - 8000:8000
    volumes:
      - ./frontend:/usr/src/app

    build:
      context: ./frontend

    depends_on:
      - database_api

  database_api:
    environment:
      - PATH_TO_DB=database.db
      - PATH_TO_CSV=db_creation/data.csv
    restart: unless-stopped

    volumes:
      - ./database_api:/usr/src/app
    build:
      context: ./database_api
  
  # uncomment when you want to run the ML Model API

#  model_api:
#    restart: unless-stopped
#
#    volumes:
#      - ./model_api:/usr/src/app
#    build:
#      context: ./model_api
  
  # uncomment when you want to run the playground

#  playground:
#    ports:
#      - 8030:8030
#    restart: unless-stopped
#
#    volumes:
#      - ./playground:/usr/src/app
#    build:
#      context: ./playground
