version: '3.8'

services:
  frontend:
    env_file:
      - '.env'
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
    volumes:
      - ./frontend:/usr/src/app
    build:
      context: ./frontend
      args:
        # pass variable so Dockerfile can use it
        FRONTEND_PORT: $FRONTEND_PORT

    depends_on:
      - database_api

  database_api:
    env_file:
      - '.env'
    # Comment out the ports line if you don't want the database API to be
    # accessible from outside the docker network
    ports:
      - $DATABASE_API_PORT:$DATABASE_API_PORT
    environment:
      - PATH_TO_DB=databases/database.db
      - PATH_TO_CSV=db_creation/csv_files/current.csv
    restart: unless-stopped

    volumes:
      - ./database_api:/usr/src/app
    build:
      context: ./database_api
  # uncomment when you want to run the ML Model API

  model_api:
    env_file:
        - '.env'
    # Comment out the ports line if you don't want the model API to be
    # accessible from outside the docker network
    ports:
      - $MODEL_API_PORT:$MODEL_API_PORT
    restart: unless-stopped
    volumes:
      - ./model_api:/usr/src/app
    build:
      context: ./model_api

  playground:
    env_file:
      - '.env'
    ports:
      - $PLAYGROUND_PORT:$PLAYGROUND_PORT
    restart: unless-stopped
    volumes:
      - ./playground:/usr/src/app
    build:
      context: ./playground
