version: '3.8'

services:
  frontend:
    env_file:
      - '.env'
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
    volumes:
      - ./frontend:/usr/src/app
    build:
      context: ./frontend
      args:
        # pass variable so Dockerfile can use it
        FRONTEND_PORT: $FRONTEND_PORT

    depends_on:
      - database_api

  database_api:
    env_file:
      - '.env'
    environment:
      - PATH_TO_DB=databases/database.db
      - PATH_TO_CSV=db_creation/csv_files/base.csv
    restart: unless-stopped

    volumes:
      - ./database_api:/usr/src/app
    build:
      context: ./database_api
  # uncomment when you want to run the ML Model API

  model_api:
    env_file:
        - '.env'
    restart: unless-stopped
    volumes:
      - ./model_api:/usr/src/app
    build:
      context: ./model_api

  # uncomment when you want to run the playground

  playground:
    env_file:
      - '.env'
    ports:
      - $PLAYGROUND_PORT:$PLAYGROUND_PORT
    restart: unless-stopped
    volumes:
      - ./playground:/usr/src/app
    build:
      context: ./playground
